import type { Comment, Listing, Profile, Report } from './types';

export const mockProfiles: Profile[] = [
  {
    id: 'profile-alina',
    nickname: 'Alina',
    avatar_url: null,
    contact: '@alina-share',
    rating: 4.9,
    created_at: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'profile-murad',
    nickname: 'Murad',
    avatar_url: null,
    contact: 'murad_cn',
    rating: 4.7,
    created_at: '2026-02-26T10:00:00.000Z',
  },
  {
    id: 'profile-jojo',
    nickname: 'JoJo',
    avatar_url: null,
    contact: 'jojo@icloud.com',
    rating: 5,
    created_at: '2026-03-03T10:00:00.000Z',
  },
];

export const mockListings: Listing[] = [
  {
    id: 'listing-apple-one-us-1',
    user_id: 'profile-alina',
    region: 'US',
    product_type: 'apple_one',
    price: 5,
    currency: 'USD',
    total_slots: 6,
    available_slots: 3,
    description: '稳定美区家庭组，账单周期固定在每月 6 日，差 3 人开车。',
    contact: '@alina-share',
    status: 'active',
    created_at: '2026-03-27T01:10:00.000Z',
  },
  {
    id: 'listing-music-tr-1',
    user_id: 'profile-murad',
    region: 'TR',
    product_type: 'music',
    price: 65,
    currency: 'TRY',
    total_slots: 6,
    available_slots: 2,
    description: 'Apple Music 土区家庭组，支持月付，已稳定使用半年。',
    contact: 'murad_cn',
    status: 'active',
    created_at: '2026-03-26T11:30:00.000Z',
  },
  {
    id: 'listing-icloud-cn-1',
    user_id: 'profile-jojo',
    region: 'CN',
    product_type: 'icloud',
    price: 12,
    currency: 'CNY',
    total_slots: 5,
    available_slots: 1,
    description: '2TB iCloud 家庭共享，主要找长期稳定用户。',
    contact: 'jojo@icloud.com',
    status: 'active',
    created_at: '2026-03-25T08:45:00.000Z',
  },
  {
    id: 'listing-apple-one-cn-1',
    user_id: 'profile-jojo',
    region: 'CN',
    product_type: 'apple_one',
    price: 20,
    currency: 'CNY',
    total_slots: 6,
    available_slots: 0,
    description: '国区 Apple One 车位刚满，展示关闭状态示例。',
    contact: 'jojo@icloud.com',
    status: 'closed',
    created_at: '2026-03-20T08:45:00.000Z',
  },
  {
    id: 'listing-music-us-1',
    user_id: 'profile-alina',
    region: 'US',
    product_type: 'music',
    price: 4.5,
    currency: 'USD',
    total_slots: 6,
    available_slots: 4,
    description: '轻量车位，接受双周结算，新用户先聊后上车。',
    contact: '@alina-share',
    status: 'active',
    created_at: '2026-03-23T08:45:00.000Z',
  },
];

export const mockComments: Comment[] = [
  {
    id: 'comment-1',
    listing_id: 'listing-apple-one-us-1',
    user_id: 'profile-jojo',
    content: '车主响应很快，补位流程清晰。',
    created_at: '2026-03-27T03:00:00.000Z',
  },
  {
    id: 'comment-2',
    listing_id: 'listing-music-tr-1',
    user_id: 'profile-alina',
    content: '付款方式已经确认，适合想压低成本的人。',
    created_at: '2026-03-26T16:00:00.000Z',
  },
];

export const mockReports: Report[] = [];
